/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoList;

public class App {

    //I don't think there needs to be anything more here
    private UserList UserL;

    // we will need the main thread here
    public static void main(String args){

    }

    // we will need our log in and log out functions here

    // our JavaFX code will also all be handled here
}
