/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoList;

import java.io.IOException;

public class App extends Application {

    // we will need the main thread here
    public static void main(String[] args){
        Application.launch(args);
    }

    @Override
    public void start(Stage stage) throws IOException{
        // we will need our log in and log out functions here

        // our JavaFX code will also all be handled here
    }

}
