/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist;

/**
 * @author Braxton Grover
 */

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

   public static UIState currentState;

    @Override
    public void start(Stage primaryStage) throws Exception {

        currentState= LoginState.instance();
        primaryStage = currentState.getStage();
        primaryStage.show();


    }


}
