/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist;

/**
 * @author Braxton Grover
 */

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

   public static UIState currentState= LoginState.instance();;
   public static void main(String[] args){
       launch();
   }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage = currentState.getStage();
        primaryStage.show();


    }


}
