/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package To.Do.List;

import javafx.application.Application;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {

    // we will need the main thread here
    public static void main(String[] args){
        Application.launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {

    }
}
